## CONFOUNDING FACTORS

In [11]:
%load_ext autoreload
%autoreload 2

# Third-party imports
import numpy as np
import pandas as pd
from bokeh.io import output_notebook

# First-party imports
from xpectral.charts import figure

output_notebook(hide_banner=True)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [12]:
rng = np.random.default_rng(42)

corr = np.array([
    [1.0, 0.8, 0.5],
    [0.8, 1.0, 0.2],
    [0.5, 0.2, 1.0],
])
n_periods = 500
chol = np.linalg.cholesky(corr)

independent = rng.standard_normal((n_periods, 3))
correlated_returns = independent @ chol.T
series = np.cumsum(correlated_returns, axis=0)

print("target correlation matrix:")
print(corr)
print("realized correlation matrix:")
print(np.round(np.corrcoef(correlated_returns, rowvar=False), 2))

target correlation matrix:
[[1.  0.8 0.5]
 [0.8 1.  0.2]
 [0.5 0.2 1. ]]
realized correlation matrix:
[[1.   0.83 0.51]
 [0.83 1.   0.26]
 [0.51 0.26 1.  ]]


In [13]:
df = pd.DataFrame(series, columns=["series 1", "series 2", "series 3"])

chart = figure(
    df,
    title="3 correlated time series (cholesky simulation)",
    x_axis_label="time",
    y_axis_label="cumulative value",
    width=700,
    height=400,
)

colors = ["#2a78d6", "#008300", "#e87ba4"]
chart.vline_stack(line_color=colors)
chart.show()